### PR TITLE
Restructure project

### PR DESCRIPTION
**Pull request by EarlPitts**
As the project has accumulated a couple of dependencies, it became a bit hard to manage them by a single makefile.
This PR restructures the project to use rebar3 for managing dependencies and building the application.

### CODE REVIEW

**Comment by EarlPitts** [comment]
I haven't added a license to the project yet.
By default rebar3 adds Apache v2 to the project, and I saw that Wrangler uses BSD.
Should I go with one of those, or maybe use GPL instead?
Does the Erlang Foundation have some guideline for this?

**Comment by simonjohnthompson** [comment]
Are you able to fix the conflicts?

**Comment by EarlPitts** [comment]
I will resolve it after the concurrency branch gets merged, because that also modifies the conflicting file.

**Comment by EarlPitts** [comment]
I've dded the license and fixed the conflicts.

**Comment by simonjohnthompson** [comment]
Accepted.

**Pull request merged**
